### ISSUE TITLE
Add instructions for changing the PIN configuration

### ISSUE THREAD

**Issue by ocdtrekkie** [limiter121/esp32-obd2-emulator#3]
I can probably find it with a little bit of exploring, but it'd be ideal to have instructions on changing the pins. I was looking at this as a possible buy to do this, which, from my understanding, should work with your project otherwise: https://www.tindie.com/products/Fusion/can32-an-esp32-dev-board-with-can-bus-v2/

**Comment by ocdtrekkie** [comment]
If I edit the sdkconfig file is that adequate? It has the "do not edit" warning at the top, but it seems like where you'd change this.

**Comment by limiter121** [comment]
Sorry for the late reply.

You can change the pins using the `make menuconfig` command.
This is mentioned in the **Build** instructions (see the note and also step 3).

Hope it helps 😉 !
