### ISSUE TITLE
Problem with http_server.h and type definitions

### ISSUE THREAD

**Issue by clfregis** [limiter121/esp32-obd2-emulator#4]
Hi, I found something that could be a problem to others (I spent all my afternoon in order to fix this), which is: Running the `makefile all` everything worked fine until a warning appeared saying: **http_server.h has been renamed to esp_http_server.h**. Then several errors showed various unknow types that supposed to be defined in http_server.h. I figured out that, for some reason, instead of including http_server.h from `.../project_file/components/http/http_server.h` it included the http_server.h from `~/esp/esp-idf/components/esp_http_server/include/http_server.h`. Thus, it could not recognize the types defined in this header file (http_server.h). I attached the output errors below.

[Error_makefile_all.txt](https://github.com/limiter121/esp32-obd2-emulator/files/3244336/Error_makefile_all.txt)

The way that I found to solve the problem was copying the folder http from `.../project_file/components/` to `.../project_file/main/` and editing line 11 of can_demo_main.c from `#include "http_server.h"` to `#include "http/http_server.h"`

Maybe redefining the includes in some way can solve the problem, but I don't have the knowledge to do so (still learning how to program properly).

**Comment by krishanddk** [comment]
On the main folder 
component.mk file
add the folder for http server like
COMPONENT_ADD_INCLUDEDIRS := . ../components/http
do not change the include file on the program

**Comment by clfregis** [comment]
Nice, Thanks for the help!!
